// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYL-wBueDnec-uaZMNg5bqiBIlfA0bmzc',
    appId: '1:723467481764:web:ac27aedfe5186f67b62c31',
    messagingSenderId: '723467481764',
    projectId: 'duan1-cee2a',
    authDomain: 'duan1-cee2a.firebaseapp.com',
    storageBucket: 'duan1-cee2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5NRBjmX1hYufWN1FVbHsT7ApzpGLv3N8',
    appId: '1:723467481764:android:d4e9f8c9f6a4a6a5b62c31',
    messagingSenderId: '723467481764',
    projectId: 'duan1-cee2a',
    storageBucket: 'duan1-cee2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYamGPDdIvuj_7J665KZsyaxO797M2tuE',
    appId: '1:723467481764:ios:a83bede48e8c428db62c31',
    messagingSenderId: '723467481764',
    projectId: 'duan1-cee2a',
    storageBucket: 'duan1-cee2a.appspot.com',
    iosClientId: '723467481764-l75c89dn7g94fhke5odurp5jrk7vihn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffemanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYamGPDdIvuj_7J665KZsyaxO797M2tuE',
    appId: '1:723467481764:ios:a83bede48e8c428db62c31',
    messagingSenderId: '723467481764',
    projectId: 'duan1-cee2a',
    storageBucket: 'duan1-cee2a.appspot.com',
    iosClientId: '723467481764-l75c89dn7g94fhke5odurp5jrk7vihn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffemanger',
  );
}
